### ISSUE TITLE
Italic the Names

### ISSUE THREAD

**Issue by jsgreenwell** [TeachingData/basic-CPP-examples#1]
The titles used for each program list (Lecture 1, Lecture 2, Lecture 3, etc...) in the readme need to be italic. This is an assignment for Networking class, which will require performing up to the pull request itself (I will only select 1 for the issue) for full credit.

**Comment by vladrph** [comment]
I updated and created a pull request. Please merge and close.

**Comment by kelvinAgramonte** [comment]
I updated and created a pull request.
